### PR TITLE
Multiple reports generated and closes #28, closes #29, closes #30, closes #31, closes #32, closes #33, closes #34, closes #35, closes #36, closes #37

### LINKED ISSUE #28: The population of people, people living in cities, and people not living in cities in each continent
As a statistician, I want to see the total population, the population living in cities, and the population not living in cities for each continent, so that I can understand urbanization patterns in different continents.

Acceptance Criteria:
The system should display the total population of each continent.
The system should display the number of people living in cities and those not living in cities for each continent.
The data should be accurate and up-to-date.
Clear labels should distinguish between the populations in cities and those not living in cities.

### LINKED ISSUE #29: The population of people, people living in cities, and people not living in cities in each region
As a statistician, I want to see the total population, the population living in cities, and the population not living in cities for each region, so that I can understand urbanization patterns within different regions.

Acceptance Criteria:
The statistician should be able to select a region.
The system should display the total population for the selected region.
The system should display the number of people living in cities and those not living in cities in the region.

### LINKED ISSUE #30: The population of people, people living in cities, and people not living in cities in each country
As a statistician, I want to see the total population, the population living in cities, and the population not living in cities for each country, so that I can understand urban and rural population distribution in specific countries.

Acceptance Criteria:
The statistician should be able to select a country.
The system should display the total population of the selected country.
The system should display the number of people living in cities and those not living in cities in the country.

### LINKED ISSUE #31: The population of the world
As a statistician, I want to know the total population of the world, so that I can understand the global population size.

Acceptance Criteria:
The system should display the current global population.

### LINKED ISSUE #32: The population of a continent
As a statistician, I want to know the total population of a specific continent, so that I can understand the population size of that continent.

Acceptance Criteria:
The statistician should be able to select a continent.
The system should display the total population of the selected continent.

### LINKED ISSUE #33: The population of a region
As a statistician, I want to know the total population of a specific region, so that I can understand the population size of that region.

Acceptance Criteria:
The statistician should be able to select a region.
The system should display the total population of the selected region.

### LINKED ISSUE #34: The population of a country
As a statistician, I want to know the total population of a specific country, so that I can understand the population size of that country.

Acceptance Criteria:
The statistician should be able to select a country.
The system should display the total population of the selected country.

### LINKED ISSUE #35: The population of a district
As a statistician, I want to know the total population of a specific district, so that I can understand the population size of that district.

Acceptance Criteria:
The statistician should be able to select a district.
The system should display the total population of the selected district.

### LINKED ISSUE #36: The population of a city
As a statistician, I want to know the total population of a specific city, so that I can understand the population size of that city.

Acceptance Criteria:
The statistician should be able to select a city.
The system should display the total population of the selected city.

### LINKED ISSUE #37: Report for specific languages in population
**As a** member of the organization,

**I want to** create a report

**so that** I can retrieve the number of people who speak the following languages in descending order, along with the percentage of the world population:
1. Chinese
2. English
3. Hindi
4. Spanish
5. Arabic

| Name  | Population | % World |
|--------|-------|------------|

### PR DESCRIPTION
**Pull request by nkoik**
@Danny-Mutale @TvonSween, can you help me with the readme table to reference the images?

### CODE REVIEW

**Comment by TvonSween** [comment]
@nkoik sure, do you mean adding the images and CSVs?

**Review by TvonSween — APPROVED** [review]

**Review by TvonSween — APPROVED** [review]

**Comment by TvonSween** [comment]
@nkoik, @Danny-Mutale, I#ve pushed the images and updated the readme with the added images on the feat/reports branch

**Comment by TvonSween** [comment]
@nkoik I've also approved the PR - thank you for doing these reports

**Comment by nkoik** [comment]
Thanks @TvonSween 

Take a look at the changes. I simplified the code so we can add only the queries fir the rest of the reports

**Comment by TvonSween** [comment]
@nkoik, yeah, nice work, that's really great.

**Review by TvonSween — APPROVED** [review]

**Pull request merged**
